# -*- coding: utf-8 -*-
"""newlp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yd405jf68WRcRg0pqOQBsaYV2BL-C1QX
"""

#!pip3  install spacy 
import  spacy
import time

nlp=spacy.load('en')  #  this  will use  nltk_data  folder  to load library

data="i am doing  great sometimes then i use feet to do not know"

#  applying  NLP   --means  tokenizing  its self 
p_data=nlp(data)

# checking  lemma and  POS 
for  i   in  p_data:
  print(i,"--Lemma-->",i.lemma_)
  time.sleep(2)
  print(" POS of  word is :  ",i.pos_)