# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vT0tR1_YW4dGR3PFbK1P-kj70gdJDIxy
"""

#!pip3  install tweepy

import  tweepy
import  time
from   textblob  import  TextBlob
import  matplotlib.pyplot  as plt

# storing consumer  key and token / secret
consumer_key = ''
consumer_secret = ''

# access key and access secret  store 
access_token=''
access_secret=''

# finding  method for  con key and  con sec
#dir(tweepy)
#  using  con key and sec  connecting to 
auth=tweepy.OAuthHandler(consumer_key,consumer_secret)

# now using this auth with  access token and secret 
auth.set_access_token(access_token,access_secret)

#  now you can connect  API 
api_connect=tweepy.API(auth)

#  now api  is connected and you can search the topic 
tweets=api_connect.search('virat',count=10)
#  printing in text form only
pos=0
neg=0
neu=0
for  tweet  in  tweets:
  analysis=TextBlob(tweet.text)
  #print(analysis.sentiment)
  if analysis.sentiment.polarity  > 0 :
    print("postive sentiment")
    pos=pos+1
  elif  analysis.sentiment.polarity  == 0 :
    print("neutral")
    neu=neu+1
  else :
    print("negative")
    neg=neg+1
  
print(pos,neg,neu)

plt.xlabel("sentiments")
plt.ylabel("count")
plt.bar(["postive","negative","neutral"],[pos,neg,neu])
plt.show()
